#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! On AKS, we disable the Admissions Enforcer so that it doesn't interfere with the webhooks included in this package.
#! See: https://github.com/cert-manager/cert-manager/issues/4114
#! See: https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces

#@ mutating_webhook = overlay.subset({"apiVersion":"admissionregistration.k8s.io/v1", "kind":"MutatingWebhookConfiguration"})
#@ validating_webhook = overlay.subset({"apiVersion":"admissionregistration.k8s.io/v1", "kind":"ValidatingWebhookConfiguration"})

#@overlay/match by=overlay.or_op(mutating_webhook,validating_webhook), expects=2
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    admissions.enforcer/disabled: "true"
