#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! Some of the OCI images used by this package are defined as arguments to containers.
#! We change the configuration to pass the image reference via environment variable
#! so that can be discovered and its digest resolved by kbld. It's a pre-requisite for supporting
#! package relocation to another registry and air-gapped scenarios.

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"cert-manager"}})
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: cert-manager-controller
          env:
            - name: CERT_MANAGER_ACMESOLVER_IMAGE
              value: quay.io/jetstack/cert-manager-acmesolver:v1.15.0
          args:
            - #@overlay/match by=lambda i,l,r: l.startswith("--acme-http01-solver-image")
              --acme-http01-solver-image=$(CERT_MANAGER_ACMESOLVER_IMAGE)
