#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"cert-manager"}})
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        #@overlay/match-child-defaults missing_ok=True
        - name: cert-manager-controller
          #@ if data.values.controller.probes.enabled:
          livenessProbe:
            httpGet:
              path: /livez
              port: http-healthz
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 8
          #@ end
