#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! Restrict Auto-Mount of Service Account Tokens.
#! See: https://cert-manager.io/docs/installation/best-practice
#! See: https://kyverno.io/policies/other/restrict-automount-sa-token/restrict-automount-sa-token

#@overlay/match by=overlay.subset({"kind":"ServiceAccount"}), expects=3
---
automountServiceAccountToken: false

#@overlay/match by=overlay.subset({"kind":"Deployment"}), expects=3
---
spec:
  template:
    #@overlay/match-child-defaults missing_ok=True
    spec:
      automountServiceAccountToken: false
      containers:
        #@overlay/match by=overlay.all
        - volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: serviceaccount-token
              readOnly: true
      volumes:
        - name: serviceaccount-token
          projected:
            defaultMode: 0444
            sources:
            - serviceAccountToken:
                expirationSeconds: 3607
                path: token
            - configMap:
                name: kube-root-ca.crt
                items:
                - key: ca.crt
                  path: ca.crt
            - downwardAPI:
                items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
