---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config

#! Search rules specify custom strategies for kbld to identify references for container images.
#! See more about the search rules: https://carvel.dev/kbld/docs/latest/config/#search-rules.
searchRules:
  
  # Resolves the image references passed via environment variables.
  - keyMatcher:
      path:
        - spec
        - template
        - spec
        - containers
        - {allIndexes: true}
        - env
        - {allIndexes: true}
        - value
  
  # Resolves the image references from the specified OCI repository.
  - valueMatcher:
      imageRepo: quay.io/jetstack
