---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config

# Search rules specify custom strategies for kbld to identify references for container images.
# See more about the search rules: https://carvel.dev/kbld/docs/latest/config/#search-rules.
searchRules:

  #! Some of the OCI images used by this package are defined as arguments to containers.
  #! We change the configuration to pass the image reference via configuration file
  #! so that can be discovered and its digest resolved by kbld. It's a pre-requisite for supporting
  #! package relocation to another registry and air-gapped scenarios.
  - keyMatcher:
      name: config.yaml
    updateStrategy:
      yaml:
        searchRules:
          - keyMatcher:
              path: [ acmeHTTP01Config, solverImage ]
