apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: cert-manager.packages.kadras.io
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp:
              rawOptions:
              - --wait-timeout=5m
              - --kube-api-qps=25
              - --kube-api-burst=50
          template:
          - ytt:
              paths:
              - config
          - kbld: {}
      export:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-cert-manager
          useKbldImagesLock: true
        includePaths:
        - config
